#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATH.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Action")]
	public partial class ActionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRel_CV_Q(Rel_CV_Q instance);
    partial void UpdateRel_CV_Q(Rel_CV_Q instance);
    partial void DeleteRel_CV_Q(Rel_CV_Q instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertDangKiThamGiaHD(DangKiThamGiaHD instance);
    partial void UpdateDangKiThamGiaHD(DangKiThamGiaHD instance);
    partial void DeleteDangKiThamGiaHD(DangKiThamGiaHD instance);
    partial void InsertDonViToChuc(DonViToChuc instance);
    partial void UpdateDonViToChuc(DonViToChuc instance);
    partial void DeleteDonViToChuc(DonViToChuc instance);
    partial void InsertHoatDong(HoatDong instance);
    partial void UpdateHoatDong(HoatDong instance);
    partial void DeleteHoatDong(HoatDong instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertQuyen(Quyen instance);
    partial void UpdateQuyen(Quyen instance);
    partial void DeleteQuyen(Quyen instance);
    #endregion
		
		public ActionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ActionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ActionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ActionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ActionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ActionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnhTrangChu> AnhTrangChus
		{
			get
			{
				return this.GetTable<AnhTrangChu>();
			}
		}
		
		public System.Data.Linq.Table<Rel_CV_Q> Rel_CV_Qs
		{
			get
			{
				return this.GetTable<Rel_CV_Q>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<DangKiThamGiaHD> DangKiThamGiaHDs
		{
			get
			{
				return this.GetTable<DangKiThamGiaHD>();
			}
		}
		
		public System.Data.Linq.Table<DonViToChuc> DonViToChucs
		{
			get
			{
				return this.GetTable<DonViToChuc>();
			}
		}
		
		public System.Data.Linq.Table<HoatDong> HoatDongs
		{
			get
			{
				return this.GetTable<HoatDong>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Quyen> Quyens
		{
			get
			{
				return this.GetTable<Quyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnhTrangChu")]
	public partial class AnhTrangChu
	{
		
		private string _Hinh1;
		
		private string _Hinh2;
		
		private string _Hinh3;
		
		public AnhTrangChu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh1", DbType="VarChar(50)")]
		public string Hinh1
		{
			get
			{
				return this._Hinh1;
			}
			set
			{
				if ((this._Hinh1 != value))
				{
					this._Hinh1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh2", DbType="VarChar(50)")]
		public string Hinh2
		{
			get
			{
				return this._Hinh2;
			}
			set
			{
				if ((this._Hinh2 != value))
				{
					this._Hinh2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh3", DbType="VarChar(50)")]
		public string Hinh3
		{
			get
			{
				return this._Hinh3;
			}
			set
			{
				if ((this._Hinh3 != value))
				{
					this._Hinh3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rel_CV_Q")]
	public partial class Rel_CV_Q : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCV_Q;
		
		private System.Nullable<int> _IdChucVu;
		
		private System.Nullable<int> _IdQuyen;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<Quyen> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCV_QChanging(int value);
    partial void OnIdCV_QChanged();
    partial void OnIdChucVuChanging(System.Nullable<int> value);
    partial void OnIdChucVuChanged();
    partial void OnIdQuyenChanging(System.Nullable<int> value);
    partial void OnIdQuyenChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public Rel_CV_Q()
		{
			this._ChucVu = default(EntityRef<ChucVu>);
			this._Quyen = default(EntityRef<Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCV_Q", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCV_Q
		{
			get
			{
				return this._IdCV_Q;
			}
			set
			{
				if ((this._IdCV_Q != value))
				{
					this.OnIdCV_QChanging(value);
					this.SendPropertyChanging();
					this._IdCV_Q = value;
					this.SendPropertyChanged("IdCV_Q");
					this.OnIdCV_QChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChucVu", DbType="Int")]
		public System.Nullable<int> IdChucVu
		{
			get
			{
				return this._IdChucVu;
			}
			set
			{
				if ((this._IdChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChucVuChanging(value);
					this.SendPropertyChanging();
					this._IdChucVu = value;
					this.SendPropertyChanged("IdChucVu");
					this.OnIdChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuyen", DbType="Int")]
		public System.Nullable<int> IdQuyen
		{
			get
			{
				return this._IdQuyen;
			}
			set
			{
				if ((this._IdQuyen != value))
				{
					if (this._Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdQuyenChanging(value);
					this.SendPropertyChanging();
					this._IdQuyen = value;
					this.SendPropertyChanged("IdQuyen");
					this.OnIdQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_Rel_CV_Q", Storage="_ChucVu", ThisKey="IdChucVu", OtherKey="IdChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.Rel_CV_Qs.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.Rel_CV_Qs.Add(this);
						this._IdChucVu = value.IdChucVu;
					}
					else
					{
						this._IdChucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_Rel_CV_Q", Storage="_Quyen", ThisKey="IdQuyen", OtherKey="IdQuyen", IsForeignKey=true)]
		public Quyen Quyen
		{
			get
			{
				return this._Quyen.Entity;
			}
			set
			{
				Quyen previousValue = this._Quyen.Entity;
				if (((previousValue != value) 
							|| (this._Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Quyen.Entity = null;
						previousValue.Rel_CV_Qs.Remove(this);
					}
					this._Quyen.Entity = value;
					if ((value != null))
					{
						value.Rel_CV_Qs.Add(this);
						this._IdQuyen = value.IdQuyen;
					}
					else
					{
						this._IdQuyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdChucVu;
		
		private string _TenChucVu;
		
		private string _MoTa;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntitySet<Rel_CV_Q> _Rel_CV_Qs;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChucVuChanging(int value);
    partial void OnIdChucVuChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public ChucVu()
		{
			this._Rel_CV_Qs = new EntitySet<Rel_CV_Q>(new Action<Rel_CV_Q>(this.attach_Rel_CV_Qs), new Action<Rel_CV_Q>(this.detach_Rel_CV_Qs));
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChucVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdChucVu
		{
			get
			{
				return this._IdChucVu;
			}
			set
			{
				if ((this._IdChucVu != value))
				{
					this.OnIdChucVuChanging(value);
					this.SendPropertyChanging();
					this._IdChucVu = value;
					this.SendPropertyChanged("IdChucVu");
					this.OnIdChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_Rel_CV_Q", Storage="_Rel_CV_Qs", ThisKey="IdChucVu", OtherKey="IdChucVu")]
		public EntitySet<Rel_CV_Q> Rel_CV_Qs
		{
			get
			{
				return this._Rel_CV_Qs;
			}
			set
			{
				this._Rel_CV_Qs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NguoiDung", Storage="_NguoiDungs", ThisKey="IdChucVu", OtherKey="IdChucVu")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rel_CV_Qs(Rel_CV_Q entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_Rel_CV_Qs(Rel_CV_Q entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKiThamGiaHD")]
	public partial class DangKiThamGiaHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDangKiHD;
		
		private System.Nullable<int> _IdInfo;
		
		private System.Nullable<int> _IdHoatDong;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<bool> _XoaTam;
		
		private System.Nullable<bool> _LayCn;
		
		private EntityRef<HoatDong> _HoatDong;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDangKiHDChanging(int value);
    partial void OnIdDangKiHDChanged();
    partial void OnIdInfoChanging(System.Nullable<int> value);
    partial void OnIdInfoChanged();
    partial void OnIdHoatDongChanging(System.Nullable<int> value);
    partial void OnIdHoatDongChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    partial void OnLayCnChanging(System.Nullable<bool> value);
    partial void OnLayCnChanged();
    #endregion
		
		public DangKiThamGiaHD()
		{
			this._HoatDong = default(EntityRef<HoatDong>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDangKiHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDangKiHD
		{
			get
			{
				return this._IdDangKiHD;
			}
			set
			{
				if ((this._IdDangKiHD != value))
				{
					this.OnIdDangKiHDChanging(value);
					this.SendPropertyChanging();
					this._IdDangKiHD = value;
					this.SendPropertyChanged("IdDangKiHD");
					this.OnIdDangKiHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInfo", DbType="Int")]
		public System.Nullable<int> IdInfo
		{
			get
			{
				return this._IdInfo;
			}
			set
			{
				if ((this._IdInfo != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdInfoChanging(value);
					this.SendPropertyChanging();
					this._IdInfo = value;
					this.SendPropertyChanged("IdInfo");
					this.OnIdInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHoatDong", DbType="Int")]
		public System.Nullable<int> IdHoatDong
		{
			get
			{
				return this._IdHoatDong;
			}
			set
			{
				if ((this._IdHoatDong != value))
				{
					if (this._HoatDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdHoatDongChanging(value);
					this.SendPropertyChanging();
					this._IdHoatDong = value;
					this.SendPropertyChanged("IdHoatDong");
					this.OnIdHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LayCn", DbType="Bit")]
		public System.Nullable<bool> LayCn
		{
			get
			{
				return this._LayCn;
			}
			set
			{
				if ((this._LayCn != value))
				{
					this.OnLayCnChanging(value);
					this.SendPropertyChanging();
					this._LayCn = value;
					this.SendPropertyChanged("LayCn");
					this.OnLayCnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoatDong_DangKiThamGiaHD", Storage="_HoatDong", ThisKey="IdHoatDong", OtherKey="IdHoatDong", IsForeignKey=true)]
		public HoatDong HoatDong
		{
			get
			{
				return this._HoatDong.Entity;
			}
			set
			{
				HoatDong previousValue = this._HoatDong.Entity;
				if (((previousValue != value) 
							|| (this._HoatDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoatDong.Entity = null;
						previousValue.DangKiThamGiaHDs.Remove(this);
					}
					this._HoatDong.Entity = value;
					if ((value != null))
					{
						value.DangKiThamGiaHDs.Add(this);
						this._IdHoatDong = value.IdHoatDong;
					}
					else
					{
						this._IdHoatDong = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoatDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DangKiThamGiaHD", Storage="_NguoiDung", ThisKey="IdInfo", OtherKey="IdInfo", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DangKiThamGiaHDs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DangKiThamGiaHDs.Add(this);
						this._IdInfo = value.IdInfo;
					}
					else
					{
						this._IdInfo = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonViToChuc")]
	public partial class DonViToChuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDonViToChuc;
		
		private string _MaDonVi;
		
		private string _TenDonVi;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntitySet<HoatDong> _HoatDongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDonViToChucChanging(int value);
    partial void OnIdDonViToChucChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public DonViToChuc()
		{
			this._HoatDongs = new EntitySet<HoatDong>(new Action<HoatDong>(this.attach_HoatDongs), new Action<HoatDong>(this.detach_HoatDongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDonViToChuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDonViToChuc
		{
			get
			{
				return this._IdDonViToChuc;
			}
			set
			{
				if ((this._IdDonViToChuc != value))
				{
					this.OnIdDonViToChucChanging(value);
					this.SendPropertyChanging();
					this._IdDonViToChuc = value;
					this.SendPropertyChanged("IdDonViToChuc");
					this.OnIdDonViToChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="Char(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(20)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this.OnTenDonViChanging(value);
					this.SendPropertyChanging();
					this._TenDonVi = value;
					this.SendPropertyChanged("TenDonVi");
					this.OnTenDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViToChuc_HoatDong", Storage="_HoatDongs", ThisKey="IdDonViToChuc", OtherKey="IdDonViToChuc")]
		public EntitySet<HoatDong> HoatDongs
		{
			get
			{
				return this._HoatDongs;
			}
			set
			{
				this._HoatDongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoatDongs(HoatDong entity)
		{
			this.SendPropertyChanging();
			entity.DonViToChuc = this;
		}
		
		private void detach_HoatDongs(HoatDong entity)
		{
			this.SendPropertyChanging();
			entity.DonViToChuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoatDong")]
	public partial class HoatDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdHoatDong;
		
		private string _TenHoatDong;
		
		private string _HinhAnh;
		
		private string _MoTaChinh;
		
		private System.Nullable<int> _GioiHanNguoiThamGia;
		
		private System.Nullable<int> _SLDaDangKi;
		
		private string _NoiDungChinhSua;
		
		private System.Nullable<bool> _XoaTam;
		
		private System.Nullable<int> _IdDonViToChuc;
		
		private string _TrangThai;
		
		private System.Nullable<int> _IdInfo;
		
		private string _Diadiem;
		
		private System.Nullable<System.DateTime> _ThoiGianBD;
		
		private System.Nullable<System.DateTime> _ThoiGianKT;
		
		private System.Nullable<System.DateTime> _ThoiGianT;
		
		private System.Nullable<System.DateTime> _ThoiGiand;
		
		private string _Background;
		
		private EntitySet<DangKiThamGiaHD> _DangKiThamGiaHDs;
		
		private EntityRef<DonViToChuc> _DonViToChuc;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHoatDongChanging(int value);
    partial void OnIdHoatDongChanged();
    partial void OnTenHoatDongChanging(string value);
    partial void OnTenHoatDongChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnMoTaChinhChanging(string value);
    partial void OnMoTaChinhChanged();
    partial void OnGioiHanNguoiThamGiaChanging(System.Nullable<int> value);
    partial void OnGioiHanNguoiThamGiaChanged();
    partial void OnSLDaDangKiChanging(System.Nullable<int> value);
    partial void OnSLDaDangKiChanged();
    partial void OnNoiDungChinhSuaChanging(string value);
    partial void OnNoiDungChinhSuaChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    partial void OnIdDonViToChucChanging(System.Nullable<int> value);
    partial void OnIdDonViToChucChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnIdInfoChanging(System.Nullable<int> value);
    partial void OnIdInfoChanged();
    partial void OnDiadiemChanging(string value);
    partial void OnDiadiemChanged();
    partial void OnThoiGianBDChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBDChanged();
    partial void OnThoiGianKTChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKTChanged();
    partial void OnThoiGianTChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTChanged();
    partial void OnThoiGiandChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGiandChanged();
    partial void OnBackgroundChanging(string value);
    partial void OnBackgroundChanged();
    #endregion
		
		public HoatDong()
		{
			this._DangKiThamGiaHDs = new EntitySet<DangKiThamGiaHD>(new Action<DangKiThamGiaHD>(this.attach_DangKiThamGiaHDs), new Action<DangKiThamGiaHD>(this.detach_DangKiThamGiaHDs));
			this._DonViToChuc = default(EntityRef<DonViToChuc>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHoatDong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdHoatDong
		{
			get
			{
				return this._IdHoatDong;
			}
			set
			{
				if ((this._IdHoatDong != value))
				{
					this.OnIdHoatDongChanging(value);
					this.SendPropertyChanging();
					this._IdHoatDong = value;
					this.SendPropertyChanged("IdHoatDong");
					this.OnIdHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoatDong", DbType="NVarChar(100)")]
		public string TenHoatDong
		{
			get
			{
				return this._TenHoatDong;
			}
			set
			{
				if ((this._TenHoatDong != value))
				{
					this.OnTenHoatDongChanging(value);
					this.SendPropertyChanging();
					this._TenHoatDong = value;
					this.SendPropertyChanged("TenHoatDong");
					this.OnTenHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaChinh", DbType="NVarChar(MAX)")]
		public string MoTaChinh
		{
			get
			{
				return this._MoTaChinh;
			}
			set
			{
				if ((this._MoTaChinh != value))
				{
					this.OnMoTaChinhChanging(value);
					this.SendPropertyChanging();
					this._MoTaChinh = value;
					this.SendPropertyChanged("MoTaChinh");
					this.OnMoTaChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiHanNguoiThamGia", DbType="Int")]
		public System.Nullable<int> GioiHanNguoiThamGia
		{
			get
			{
				return this._GioiHanNguoiThamGia;
			}
			set
			{
				if ((this._GioiHanNguoiThamGia != value))
				{
					this.OnGioiHanNguoiThamGiaChanging(value);
					this.SendPropertyChanging();
					this._GioiHanNguoiThamGia = value;
					this.SendPropertyChanged("GioiHanNguoiThamGia");
					this.OnGioiHanNguoiThamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLDaDangKi", DbType="Int")]
		public System.Nullable<int> SLDaDangKi
		{
			get
			{
				return this._SLDaDangKi;
			}
			set
			{
				if ((this._SLDaDangKi != value))
				{
					this.OnSLDaDangKiChanging(value);
					this.SendPropertyChanging();
					this._SLDaDangKi = value;
					this.SendPropertyChanged("SLDaDangKi");
					this.OnSLDaDangKiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungChinhSua", DbType="NVarChar(MAX)")]
		public string NoiDungChinhSua
		{
			get
			{
				return this._NoiDungChinhSua;
			}
			set
			{
				if ((this._NoiDungChinhSua != value))
				{
					this.OnNoiDungChinhSuaChanging(value);
					this.SendPropertyChanging();
					this._NoiDungChinhSua = value;
					this.SendPropertyChanged("NoiDungChinhSua");
					this.OnNoiDungChinhSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDonViToChuc", DbType="Int")]
		public System.Nullable<int> IdDonViToChuc
		{
			get
			{
				return this._IdDonViToChuc;
			}
			set
			{
				if ((this._IdDonViToChuc != value))
				{
					if (this._DonViToChuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdDonViToChucChanging(value);
					this.SendPropertyChanging();
					this._IdDonViToChuc = value;
					this.SendPropertyChanged("IdDonViToChuc");
					this.OnIdDonViToChucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(20)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInfo", DbType="Int")]
		public System.Nullable<int> IdInfo
		{
			get
			{
				return this._IdInfo;
			}
			set
			{
				if ((this._IdInfo != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdInfoChanging(value);
					this.SendPropertyChanging();
					this._IdInfo = value;
					this.SendPropertyChanged("IdInfo");
					this.OnIdInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diadiem", DbType="NVarChar(100)")]
		public string Diadiem
		{
			get
			{
				return this._Diadiem;
			}
			set
			{
				if ((this._Diadiem != value))
				{
					this.OnDiadiemChanging(value);
					this.SendPropertyChanging();
					this._Diadiem = value;
					this.SendPropertyChanged("Diadiem");
					this.OnDiadiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBD
		{
			get
			{
				return this._ThoiGianBD;
			}
			set
			{
				if ((this._ThoiGianBD != value))
				{
					this.OnThoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBD = value;
					this.SendPropertyChanged("ThoiGianBD");
					this.OnThoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKT
		{
			get
			{
				return this._ThoiGianKT;
			}
			set
			{
				if ((this._ThoiGianKT != value))
				{
					this.OnThoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKT = value;
					this.SendPropertyChanged("ThoiGianKT");
					this.OnThoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianT
		{
			get
			{
				return this._ThoiGianT;
			}
			set
			{
				if ((this._ThoiGianT != value))
				{
					this.OnThoiGianTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianT = value;
					this.SendPropertyChanged("ThoiGianT");
					this.OnThoiGianTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGiand", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGiand
		{
			get
			{
				return this._ThoiGiand;
			}
			set
			{
				if ((this._ThoiGiand != value))
				{
					this.OnThoiGiandChanging(value);
					this.SendPropertyChanging();
					this._ThoiGiand = value;
					this.SendPropertyChanged("ThoiGiand");
					this.OnThoiGiandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Background", DbType="VarChar(50)")]
		public string Background
		{
			get
			{
				return this._Background;
			}
			set
			{
				if ((this._Background != value))
				{
					this.OnBackgroundChanging(value);
					this.SendPropertyChanging();
					this._Background = value;
					this.SendPropertyChanged("Background");
					this.OnBackgroundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoatDong_DangKiThamGiaHD", Storage="_DangKiThamGiaHDs", ThisKey="IdHoatDong", OtherKey="IdHoatDong")]
		public EntitySet<DangKiThamGiaHD> DangKiThamGiaHDs
		{
			get
			{
				return this._DangKiThamGiaHDs;
			}
			set
			{
				this._DangKiThamGiaHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonViToChuc_HoatDong", Storage="_DonViToChuc", ThisKey="IdDonViToChuc", OtherKey="IdDonViToChuc", IsForeignKey=true)]
		public DonViToChuc DonViToChuc
		{
			get
			{
				return this._DonViToChuc.Entity;
			}
			set
			{
				DonViToChuc previousValue = this._DonViToChuc.Entity;
				if (((previousValue != value) 
							|| (this._DonViToChuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonViToChuc.Entity = null;
						previousValue.HoatDongs.Remove(this);
					}
					this._DonViToChuc.Entity = value;
					if ((value != null))
					{
						value.HoatDongs.Add(this);
						this._IdDonViToChuc = value.IdDonViToChuc;
					}
					else
					{
						this._IdDonViToChuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("DonViToChuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_HoatDong", Storage="_NguoiDung", ThisKey="IdInfo", OtherKey="IdInfo", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.HoatDongs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.HoatDongs.Add(this);
						this._IdInfo = value.IdInfo;
					}
					else
					{
						this._IdInfo = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKiThamGiaHDs(DangKiThamGiaHD entity)
		{
			this.SendPropertyChanging();
			entity.HoatDong = this;
		}
		
		private void detach_DangKiThamGiaHDs(DangKiThamGiaHD entity)
		{
			this.SendPropertyChanging();
			entity.HoatDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLop;
		
		private string _TenLop;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLopChanging(int value);
    partial void OnIdLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public Lop()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLop", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLop
		{
			get
			{
				return this._IdLop;
			}
			set
			{
				if ((this._IdLop != value))
				{
					this.OnIdLopChanging(value);
					this.SendPropertyChanging();
					this._IdLop = value;
					this.SendPropertyChanged("IdLop");
					this.OnIdLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="Char(10)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_NguoiDung", Storage="_NguoiDungs", ThisKey="IdLop", OtherKey="IdLop")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdInfo;
		
		private string _SoId;
		
		private string _Ho_Ten;
		
		private string _SDT;
		
		private System.Nullable<int> _IdChucVu;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<int> _IdLop;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntitySet<DangKiThamGiaHD> _DangKiThamGiaHDs;
		
		private EntitySet<HoatDong> _HoatDongs;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdInfoChanging(int value);
    partial void OnIdInfoChanged();
    partial void OnSoIdChanging(string value);
    partial void OnSoIdChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnIdChucVuChanging(System.Nullable<int> value);
    partial void OnIdChucVuChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnIdLopChanging(System.Nullable<int> value);
    partial void OnIdLopChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public NguoiDung()
		{
			this._DangKiThamGiaHDs = new EntitySet<DangKiThamGiaHD>(new Action<DangKiThamGiaHD>(this.attach_DangKiThamGiaHDs), new Action<DangKiThamGiaHD>(this.detach_DangKiThamGiaHDs));
			this._HoatDongs = new EntitySet<HoatDong>(new Action<HoatDong>(this.attach_HoatDongs), new Action<HoatDong>(this.detach_HoatDongs));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInfo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdInfo
		{
			get
			{
				return this._IdInfo;
			}
			set
			{
				if ((this._IdInfo != value))
				{
					this.OnIdInfoChanging(value);
					this.SendPropertyChanging();
					this._IdInfo = value;
					this.SendPropertyChanged("IdInfo");
					this.OnIdInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoId", DbType="Char(11)")]
		public string SoId
		{
			get
			{
				return this._SoId;
			}
			set
			{
				if ((this._SoId != value))
				{
					this.OnSoIdChanging(value);
					this.SendPropertyChanging();
					this._SoId = value;
					this.SendPropertyChanged("SoId");
					this.OnSoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(100)")]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this.OnHo_TenChanging(value);
					this.SendPropertyChanging();
					this._Ho_Ten = value;
					this.SendPropertyChanged("Ho_Ten");
					this.OnHo_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdChucVu", DbType="Int")]
		public System.Nullable<int> IdChucVu
		{
			get
			{
				return this._IdChucVu;
			}
			set
			{
				if ((this._IdChucVu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChucVuChanging(value);
					this.SendPropertyChanging();
					this._IdChucVu = value;
					this.SendPropertyChanged("IdChucVu");
					this.OnIdChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(10)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(MAX)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLop", DbType="Int")]
		public System.Nullable<int> IdLop
		{
			get
			{
				return this._IdLop;
			}
			set
			{
				if ((this._IdLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLopChanging(value);
					this.SendPropertyChanging();
					this._IdLop = value;
					this.SendPropertyChanged("IdLop");
					this.OnIdLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DangKiThamGiaHD", Storage="_DangKiThamGiaHDs", ThisKey="IdInfo", OtherKey="IdInfo")]
		public EntitySet<DangKiThamGiaHD> DangKiThamGiaHDs
		{
			get
			{
				return this._DangKiThamGiaHDs;
			}
			set
			{
				this._DangKiThamGiaHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_HoatDong", Storage="_HoatDongs", ThisKey="IdInfo", OtherKey="IdInfo")]
		public EntitySet<HoatDong> HoatDongs
		{
			get
			{
				return this._HoatDongs;
			}
			set
			{
				this._HoatDongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NguoiDung", Storage="_ChucVu", ThisKey="IdChucVu", OtherKey="IdChucVu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._IdChucVu = value.IdChucVu;
					}
					else
					{
						this._IdChucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_NguoiDung", Storage="_Lop", ThisKey="IdLop", OtherKey="IdLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._IdLop = value.IdLop;
					}
					else
					{
						this._IdLop = default(Nullable<int>);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKiThamGiaHDs(DangKiThamGiaHD entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DangKiThamGiaHDs(DangKiThamGiaHD entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_HoatDongs(HoatDong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_HoatDongs(HoatDong entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quyen")]
	public partial class Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdQuyen;
		
		private string _TenQuyen;
		
		private string _MoTa;
		
		private System.Nullable<bool> _XoaTam;
		
		private EntitySet<Rel_CV_Q> _Rel_CV_Qs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdQuyenChanging(int value);
    partial void OnIdQuyenChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnXoaTamChanging(System.Nullable<bool> value);
    partial void OnXoaTamChanged();
    #endregion
		
		public Quyen()
		{
			this._Rel_CV_Qs = new EntitySet<Rel_CV_Q>(new Action<Rel_CV_Q>(this.attach_Rel_CV_Qs), new Action<Rel_CV_Q>(this.detach_Rel_CV_Qs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdQuyen
		{
			get
			{
				return this._IdQuyen;
			}
			set
			{
				if ((this._IdQuyen != value))
				{
					this.OnIdQuyenChanging(value);
					this.SendPropertyChanging();
					this._IdQuyen = value;
					this.SendPropertyChanged("IdQuyen");
					this.OnIdQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(50)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XoaTam", DbType="Bit")]
		public System.Nullable<bool> XoaTam
		{
			get
			{
				return this._XoaTam;
			}
			set
			{
				if ((this._XoaTam != value))
				{
					this.OnXoaTamChanging(value);
					this.SendPropertyChanging();
					this._XoaTam = value;
					this.SendPropertyChanged("XoaTam");
					this.OnXoaTamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Quyen_Rel_CV_Q", Storage="_Rel_CV_Qs", ThisKey="IdQuyen", OtherKey="IdQuyen")]
		public EntitySet<Rel_CV_Q> Rel_CV_Qs
		{
			get
			{
				return this._Rel_CV_Qs;
			}
			set
			{
				this._Rel_CV_Qs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rel_CV_Qs(Rel_CV_Q entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = this;
		}
		
		private void detach_Rel_CV_Qs(Rel_CV_Q entity)
		{
			this.SendPropertyChanging();
			entity.Quyen = null;
		}
	}
}
#pragma warning restore 1591
